const visit = require('unist-util-visit')
const puppeteer = require('puppeteer')
const render = require('./render')

const EOL = '\n'

const importLine = `import Mermaid from '@prose/gatsby-remark-mermaid/Mermaid'`

const isImportExists = tree => {
  let exists = false

  visit(tree, 'import', node => {
    if (node.value && node.value.includes(importLine)) {
      exists = true
    }
  })

  return exists
}

const mermaidNodes = (markdownAST, language) => {
  const result = []

  visit(markdownAST, 'code', node => {
    if ((node.lang || '').toLowerCase() === language) {
      result.push(node)
    }
  })

  return result
}

const addImport = (tree, importValue) => {
  // TODO: review, as position property is not set
  tree.children = [{ type: 'import', value: importValue }, ...tree.children]
}

const plugin = async ({ markdownAST }, options) => {
  const defaultPre = value => value

  const defaultPost = value => {
    // replace braces interpreted as JSX vars
    let val = value.replace(/{/g, '[').replace(/}/g, ']')

    // remove inline styles generated by mermaid
    return val.replace(/<style>.*?<\/style>/gms, '')
  }

  const { language = 'mermaid' } = options || {}
  const { viewport = { height: 200, width: 200 } } = options || {}
  const { mermaidOptions = {} } = options || {}
  const { pre = defaultPre, post = defaultPost } = options

  if (!isImportExists(markdownAST)) {
    addImport(markdownAST, importLine)
  }

  const nodes = mermaidNodes(markdownAST, language)
  if (nodes.length === 0) {
    return
  }

  const browser = await puppeteer.launch({
    args: ['--no-sandbox', '--disable-setuid-sandbox'],
  })

  const toMermaidComponent = async value => {
    const val = pre(value)

    let svg = await render(browser, val, 'default', viewport, mermaidOptions)
    svg = post(svg)

    return `<Mermaid>${EOL}${EOL}${svg}${EOL}${EOL}</Mermaid>`
  }

  await Promise.all(
    nodes.map(async node => {
      node.type = 'jsx'
      node.value = await toMermaidComponent(node.value)
    })
  )
}

module.exports = plugin
