const visit = require('unist-util-visit')
const puppeteer = require('puppeteer')
const render = require('./render')

const EOL = '\n'

const importLine = `import Mermaid from '@prose/gatsby-remark-mermaid/Mermaid'`

const isImportExists = tree => {
  let exists = false

  visit(tree, 'import', node => {
    if (node.value && node.value.includes(importLine)) {
      exists = true
    }
  })

  return exists
}

const mermaidNodes = (markdownAST, language) => {
  const result = []

  visit(markdownAST, 'code', node => {
    if ((node.lang || '').toLowerCase() === language) {
      result.push(node)
    }
  })

  return result
}

const addImport = (tree, importValue) => {
  // TODO: review, as position property is not set
  tree.children = [{ type: 'import', value: importValue }, ...tree.children]
}

const plugin = async ({ markdownAST }, options) => {
  const defaultPreRender = value => value

  const defaultPostRender = value => {
    if (!value) {
      return value
    }

    // replace braces interpreted as JSX vars
    // see https://github.com/facebook/react/issues/1545
    let val = value.replace(/([{}]+)/g, "{'$1'}")

    // remove inline styles generated by mermaid
    return val.replace(/<style>.*?<\/style>/gms, '')
  }

  const { language = 'mermaid' } = options || {}
  const { viewport = { height: 200, width: 200 } } = options || {}
  const { mermaidOptions = {} } = options || {}
  const {
    preRender = defaultPreRender,
    postRender = defaultPostRender,
  } = options

  if (!isImportExists(markdownAST)) {
    addImport(markdownAST, importLine)
  }

  const nodes = mermaidNodes(markdownAST, language)
  if (nodes.length === 0) {
    return
  }

  const browser = await puppeteer.launch({
    args: ['--no-sandbox', '--disable-setuid-sandbox'],
  })

  const toMermaidComponent = async value => {
    const val = preRender(value)

    let svg = await render(browser, val, 'default', viewport, mermaidOptions)
    svg = postRender(svg)

    return `<Mermaid>${EOL}${EOL}${svg}${EOL}${EOL}</Mermaid>`
  }

  await Promise.all(
    nodes.map(async node => {
      node.type = 'jsx'
      node.value = await toMermaidComponent(node.value)
    })
  )
}

module.exports = plugin
