const visit = require('unist-util-visit')
const modifyChildren = require('unist-util-modify-children')
const puppeteer = require('puppeteer')
const render = require('./render')

const EOL = '\n'

const importLine = `import Mermaid from '@prose/remark-mermaid/Mermaid'`

const isImportExists = tree => {
  let exists = false

  visit(tree, 'import', node => {
    if (node.value && node.value.includes(importLine)) {
      exists = true
    }
  })

  return exists
}

const mermaidNodes = (markdownAST, language) => {
  const result = []

  visit(markdownAST, 'code', node => {
    if ((node.lang || '').toLowerCase() === language) {
      result.push(node)
    }
  })

  return result
}

const plugin = async (
  { markdownAST },
  {
    language = 'mermaid',
    theme = 'default',
    viewport = { height: 200, width: 200 },
    mermaidOptions = {},
  }
) => {
  if (!isImportExists(markdownAST)) {
    const modify = modifyChildren((_, index, parent) => {
      if (index === 0) {
        parent.children.splice(index, 1, { type: 'import', value: importLine })
        return index + 1
      }
    })

    modify(markdownAST)
  }

  const nodes = mermaidNodes(markdownAST, language)
  if (nodes.length === 0) {
    return
  }

  const browser = await puppeteer.launch({
    args: ['--no-sandbox', '--disable-setuid-sandbox'],
  })

  const toMermaidComponent = async value => {
    const svg = await render(browser, value, theme, viewport, mermaidOptions)

    // remove inline styles generated by mermaid, as it is invalid JSX
    const cleanedSvg = svg.replace(/<style>.*?<\/style>/gms, '')
    return `<Mermaid>${EOL}${EOL}${cleanedSvg}${EOL}${EOL}</Mermaid>`
  }

  await Promise.all(
    nodes.map(async node => {
      node.type = 'jsx'
      node.value = await toMermaidComponent(node.value)
    })
  )
}

module.exports = plugin
